from datetime import datetime,time,timedelta,date
from db import Session
from models import Stop

TRAMVAJE = [{'trasa' : [{'id':4001, 'cas':timedelta(0)},
                        {'id':4015, 'cas':timedelta(minutes=12)}],
            'intervaly' : [{'od': time(hour=4,minute=36),
                            'do': time(hour=19,minute=56),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=20,minute=10),
                            'do': time(hour=22,minute=10),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=22, minute=30),
                            'do': time(hour=23, minute=00),
                            'interval': timedelta(minutes=30)}
                           ],
            'basecislo' : 3000000,
            'name': 'Liberec Lidové sady -> Nádraží'},
            {'trasa': [{'id': 4015, 'cas': timedelta(0)},
                       {'id': 4001, 'cas': timedelta(minutes=13)}],
             'intervaly': [{'od': time(hour=4, minute=38),
                            'do': time(hour=19, minute=48),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=19, minute=58),
                            'do': time(hour=22, minute=13),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=22, minute=33),
                            'do': time(hour=23, minute=3),
                            'interval': timedelta(minutes=30)}
                           ],
             'basecislo': 3000001,
             'name': 'Liberec Nádraží -> Lidové sady'},
            {'trasa': [{'id': 4002, 'cas': timedelta(0)},
                       {'id': 4014, 'cas': timedelta(minutes=8)}],
             'intervaly': [{'od': time(hour=4, minute=42),
                            'do': time(hour=5, minute=18),
                            'interval': timedelta(minutes=12)},
                           {'od': time(hour=5, minute=33),
                            'do': time(hour=19, minute=3),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=19, minute=13),
                             'do': time(hour=23, minute=13),
                             'interval': timedelta(minutes=15)}],
             'basecislo': 4000000,
             'name': 'Olomouc Pavlovičky -> Nádraží'},
            {'trasa': [{'id': 4014, 'cas': timedelta(0)},
                       {'id': 4002, 'cas': timedelta(minutes=8)}],
             'intervaly': [{'od': time(hour=4, minute=32),
                            'do': time(hour=5, minute=47),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=6, minute=4),
                            'do': time(hour=19, minute=4),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=19, minute=17),
                             'do': time(hour=23, minute=2),
                             'interval': timedelta(minutes=15)}],
             'basecislo': 4000001,
             'name': 'Olomouc Nádraží -> Pavlovičky'},
            {'trasa': [{'id': 4003, 'cas': timedelta(0)},
                       {'id': 4013, 'cas': timedelta(minutes=10)}],
             'intervaly': [{'od': time(hour=0, minute=14),
                            'do': time(hour=3, minute=14),
                            'interval': timedelta(minutes=60)},
                            {'od': time(hour=0, minute=49),
                            'do': time(hour=3, minute=49),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=4, minute=1),
                            'do': time(hour=4, minute=31),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=4, minute=36),
                            'do': time(hour=23, minute=11),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=23, minute=17),
                            'do': time(hour=23, minute=49),
                            'interval': timedelta(minutes=10)}
                           ],
             'basecislo': 8000000,
             'name': 'Ostrava Karolina -> Nádraží'},
            {'trasa': [{'id': 4013, 'cas': timedelta(0)},
                       {'id': 4003, 'cas': timedelta(minutes=10)}],
             'intervaly': [{'od': time(hour=0, minute=15),
                            'do': time(hour=3, minute=15),
                            'interval': timedelta(minutes=60)},
                            {'od': time(hour=0, minute=50),
                            'do': time(hour=3, minute=50),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=4, minute=6),
                            'do': time(hour=4, minute=30),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=4, minute=34),
                            'do': time(hour=22, minute=34),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=22, minute=40),
                            'do': time(hour=22, minute=50),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=23, minute=5),
                            'do': time(hour=23, minute=15),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=23, minute=36),
                            'do': time(hour=23, minute=50),
                            'interval': timedelta(minutes=14)}
                           ],
             'basecislo': 8000001,
             'name': 'Ostrava Nádraží -> Karolina'},
            {'trasa': [{'id': 4003, 'cas': timedelta(0)},
                       {'id': 4012, 'cas': timedelta(minutes=15)}],
             'intervaly': [{'od': time(hour=0, minute=3),
                            'do': time(hour=4, minute=3),
                            'interval': timedelta(minutes=60)},
                            {'od': time(hour=0, minute=27),
                            'do': time(hour=3, minute=27),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=4, minute=17),
                            'do': time(hour=4, minute=41),
                            'interval': timedelta(minutes=8)},
                           {'od': time(hour=4, minute=48),
                            'do': time(hour=5, minute=58),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=6, minute=10),
                            'do': time(hour=8, minute=25),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=6, minute=14),
                            'do': time(hour=8, minute=29),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=6, minute=6),
                            'do': time(hour=8, minute=36),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=8, minute=37),
                            'do': time(hour=13, minute=32),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=13, minute=40),
                            'do': time(hour=17, minute=55),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=13, minute=36),
                            'do': time(hour=17, minute=36),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=13, minute=44),
                            'do': time(hour=17, minute=44),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=17, minute=49),
                            'do': time(hour=19, minute=39),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=18, minute=4),
                            'do': time(hour=19, minute=44),
                            'interval': timedelta(minutes=20)},
                           {'od': time(hour=19, minute=52),
                            'do': time(hour=22, minute=52),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=19, minute=58),
                            'do': time(hour=22, minute=58),
                            'interval': timedelta(minutes=20)},
                           {'od': time(hour=23, minute=3),
                            'do': time(hour=23, minute=18),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=23, minute=27),
                            'do': time(hour=23, minute=48),
                            'interval': timedelta(minutes=7)}],
             'basecislo': 8100000,
             'name': 'Ostrava Karolina -> Svinov'},
            {'trasa': [{'id': 4012, 'cas': timedelta(0)},
                       {'id': 4003, 'cas': timedelta(minutes=15)}],
             'intervaly': [{'od': time(hour=0, minute=35),
                            'do': time(hour=3, minute=35),
                            'interval': timedelta(minutes=60)},
                            {'od': time(hour=0, minute=59),
                            'do': time(hour=3, minute=59),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=3, minute=18),
                            'do': time(hour=3, minute=24),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=3, minute=42),
                            'do': time(hour=3, minute=48),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=4, minute=12),
                            'do': time(hour=5, minute=36),
                            'interval': timedelta(minutes=4)},
                           {'od': time(hour=5, minute=48),
                            'do': time(hour=8, minute=33),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=5, minute=37),
                            'do': time(hour=8, minute=22),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=5, minute=44),
                            'do': time(hour=8, minute=29),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=8, minute=31),
                            'do': time(hour=13, minute=1),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=13, minute=3),
                            'do': time(hour=17, minute=3),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=13, minute=7),
                            'do': time(hour=17, minute=7),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=13, minute=14),
                            'do': time(hour=17, minute=14),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=17, minute=19),
                            'do': time(hour=17, minute=44),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=17, minute=54),
                            'do': time(hour=19, minute=24),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=17, minute=59),
                            'do': time(hour=19, minute=19),
                            'interval': timedelta(minutes=20)},
                           {'od': time(hour=19, minute=36),
                            'do': time(hour=22, minute=36),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=19, minute=40),
                            'do': time(hour=22, minute=40),
                            'interval': timedelta(minutes=20)},
                           {'od': time(hour=22, minute=59),
                            'do': time(hour=23, minute=59),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=23, minute=35),
                            'do': time(hour=23, minute=35),
                            'interval': timedelta(minutes=60)}],
             'basecislo': 8100001,
             'name': 'Ostrava Svinov -> Karolina'},
            {'trasa': [{'id': 4010, 'cas': timedelta(0)},
                       {'id': 4004, 'cas': timedelta(minutes=8)},
                       {'id': 4011, 'cas': timedelta(minutes=24)},
                       {'id': 4005, 'cas': timedelta(minutes=32)}],
             'intervaly': [{'od': time(hour=3, minute=12),
                            'do': time(hour=4, minute=0),
                            'interval': timedelta(minutes=48)},
                           {'od': time(hour=4, minute=20),
                            'do': time(hour=18, minute=50),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=23, minute=25),
                             'do': time(hour=23, minute=25),
                             'interval': timedelta(minutes=60)},
                            {'od': time(hour=4, minute=56),
                             'do': time(hour=5, minute=26),
                             'interval': timedelta(minutes=15)}
                           ],
             'basecislo': 2000000,
             'name': 'Most -> Litvínov'},
            {'trasa': [{'id': 4010, 'cas': timedelta(0)},
                       {'id': 4004, 'cas': timedelta(minutes=15)},
                       {'id': 4011, 'cas': timedelta(minutes=31)},
                       {'id': 4005, 'cas': timedelta(minutes=39)}],
             'intervaly': [{'od': time(hour=19, minute=1),
                            'do': time(hour=19, minute=31),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=20, minute=1),
                            'do': time(hour=22, minute=31),
                            'interval': timedelta(minutes=30)},
                           {'od': time(hour=13, minute=4),
                            'do': time(hour=15, minute=4),
                            'interval': timedelta(minutes=15)}
                           ],
             'basecislo': 2100000,
             'name': 'Most -> Litvínov (pomala)'},
            {'trasa': [{'id': 4005, 'cas': timedelta(0)},
                       {'id': 4011, 'cas': timedelta(minutes=8)},
                       {'id': 4004, 'cas': timedelta(minutes=24)},
                       {'id': 4010, 'cas': timedelta(minutes=32)}],
             'intervaly': [{'od': time(hour=0, minute=6),
                            'do': time(hour=0, minute=6),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=3, minute=51),
                            'do': time(hour=4, minute=16),
                            'interval': timedelta(minutes=25)},
                            {'od': time(hour=4, minute=36),
                            'do': time(hour=19, minute=6),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=4, minute=57),
                            'do': time(hour=5, minute=57),
                            'interval': timedelta(minutes=15)}
                           ],
             'basecislo': 2000001,
             'name': 'Litvínov -> Most'},
            {'trasa': [{'id': 4005, 'cas': timedelta(0)},
                       {'id': 4011, 'cas': timedelta(minutes=8)},
                       {'id': 4004, 'cas': timedelta(minutes=24)},
                       {'id': 4010, 'cas': timedelta(minutes=39)}],
             'intervaly': [{'od': time(hour=19, minute=22),
                            'do': time(hour=22, minute=22),
                            'interval': timedelta(minutes=30)},
                           {'od': time(hour=21, minute=5),
                            'do': time(hour=22, minute=5),
                            'interval': timedelta(minutes=60)},
                           {'od': time(hour=4, minute=36),
                            'do': time(hour=19, minute=6),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=6, minute=12),
                            'do': time(hour=6, minute=57),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=12, minute=57),
                            'do': time(hour=13, minute=12),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=13, minute=57),
                            'do': time(hour=15, minute=27),
                            'interval': timedelta(minutes=15)}
                           ],
             'basecislo': 2100001,
             'name': 'Litvínov -> Most (pomalá)'},
            {'trasa': [{'id': 4006, 'cas': timedelta(0)},
                       {'id': 4009, 'cas': timedelta(minutes=15)}],
             'intervaly': [{'od': time(hour=4, minute=38),
                            'do': time(hour=8, minute=0),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=8, minute=6),
                            'do': time(hour=13, minute=16),
                            'interval': timedelta(minutes=10)},
                            {'od': time(hour=13, minute=23),
                            'do': time(hour=17, minute=53),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=13, minute=31),
                            'do': time(hour=18, minute=1),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=18, minute=10),
                            'do': time(hour=18, minute=26),
                            'interval': timedelta(minutes=8)},
                            {'od': time(hour=18, minute=34),
                            'do': time(hour=22, minute=24),
                            'interval': timedelta(minutes=10)},
                            {'od': time(hour=22, minute=38),
                            'do': time(hour=23, minute=38),
                            'interval': timedelta(minutes=15)}
                           ],
             'basecislo': 1000000,
             'name': 'Plzeň Bolevec -> Nádraží'},
            {'trasa': [{'id': 4009, 'cas': timedelta(0)},
                       {'id': 4006, 'cas': timedelta(minutes=15)}],
             'intervaly': [{'od': time(hour=4, minute=17),
                            'do': time(hour=7, minute=28),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=7, minute=35),
                            'do': time(hour=12, minute=25),
                            'interval': timedelta(minutes=10)},
                            {'od': time(hour=12, minute=34),
                            'do': time(hour=17, minute=34),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=12, minute=42),
                            'do': time(hour=17, minute=42),
                            'interval': timedelta(minutes=15)},
                            {'od': time(hour=17, minute=52),
                            'do': time(hour=22, minute=32),
                            'interval': timedelta(minutes=10)},
                            {'od': time(hour=22, minute=44),
                            'do': time(hour=23, minute=44),
                            'interval': timedelta(minutes=30)}],
             'basecislo': 1000001,
             'name': 'Plzeň Nádraží -> Bolevec'},
            {'trasa': [{'id': 4007, 'cas': timedelta(0)},
                       {'id': 4008, 'cas': timedelta(minutes=16)}],
             'intervaly': [{'od': time(hour=4, minute=35),
                            'do': time(hour=4, minute=46),
                            'interval': timedelta(minutes=11)},
                           {'od': time(hour=4, minute=53),
                            'do': time(hour=5, minute=0),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=5, minute=3),
                            'do': time(hour=7, minute=48),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=7, minute=53),
                            'do': time(hour=12, minute=53),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=8, minute=0),
                            'do': time(hour=13, minute=0),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=13, minute=6),
                            'do': time(hour=13, minute=48),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=13, minute=53),
                            'do': time(hour=17, minute=38),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=17, minute=44),
                            'do': time(hour=18, minute=20),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=18, minute=27),
                            'do': time(hour=20, minute=5),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=20, minute=14),
                            'do': time(hour=22, minute=24),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=22, minute=37),
                            'do': time(hour=23, minute=37),
                            'interval': timedelta(minutes=15)}
                           ],
             'basecislo': 1100000,
             'name': 'Plzeň Košutka -> Chodské náměstí'},
            {'trasa': [{'id': 4008, 'cas': timedelta(0)},
                       {'id': 4007, 'cas': timedelta(minutes=16)}],
             'intervaly': [{'od': time(hour=4, minute=43),
                            'do': time(hour=4, minute=59),
                            'interval': timedelta(minutes=16)},
                           {'od': time(hour=5, minute=10),
                            'do': time(hour=5, minute=28),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=5, minute=33),
                            'do': time(hour=7, minute=43),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=7, minute=49),
                            'do': time(hour=8, minute=7),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=8, minute=14),
                            'do': time(hour=12, minute=44),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=8, minute=22),
                            'do': time(hour=12, minute=37),
                            'interval': timedelta(minutes=15)},
                           {'od': time(hour=12, minute=51),
                            'do': time(hour=13, minute=33),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=13, minute=40),
                            'do': time(hour=13, minute=58),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=14, minute=3),
                            'do': time(hour=17, minute=48),
                            'interval': timedelta(minutes=5)},
                           {'od': time(hour=17, minute=54),
                            'do': time(hour=18, minute=0),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=18, minute=7),
                            'do': time(hour=18, minute=14),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=18, minute=20),
                            'do': time(hour=18, minute=26),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=18, minute=33),
                            'do': time(hour=18, minute=45),
                            'interval': timedelta(minutes=6)},
                           {'od': time(hour=18, minute=53),
                            'do': time(hour=19, minute=42),
                            'interval': timedelta(minutes=7)},
                           {'od': time(hour=19, minute=50),
                            'do': time(hour=20, minute=14),
                            'interval': timedelta(minutes=8)},
                           {'od': time(hour=20, minute=22),
                            'do': time(hour=22, minute=32),
                            'interval': timedelta(minutes=10)},
                           {'od': time(hour=22, minute=27),
                            'do': time(hour=22, minute=39),
                            'interval': timedelta(minutes=12)},
                           {'od': time(hour=22, minute=44),
                            'do': time(hour=23, minute=44),
                            'interval': timedelta(minutes=15)}],
             'basecislo': 1100001,
             'name': 'Plzeň Chodské náměstí -> Košutka'},
            ]
den = date(day=10, month=8, year=2022)
session = Session()

for linka in TRAMVAJE:
    curr_cislo = linka['basecislo']
    for interval in linka['intervaly']:
        curr_time = datetime.combine(den,interval['od'])
        while curr_time <= datetime.combine(den,interval['do']):
            for i,stop in enumerate(linka['trasa']):
                new_stop = Stop(bod_id=stop['id'],kategorie='tram',vlak_id=curr_cislo,poradi=i+1)
                new_stop.vlak = new_stop.kategorie + ' ' + str(new_stop.vlak_id)
                if i != len(linka['trasa'])-1:
                    odj = curr_time + stop['cas']
                    new_stop.odjezd = odj.time()
                    if odj.date() > den:
                        new_stop.ddo = True
                if i != 0:
                    prij = curr_time + stop['cas']
                    new_stop.prijezd = prij.time()
                    if prij.date() > den:
                        new_stop.ddp = True
                session.add(new_stop)
            curr_time = curr_time + interval['interval']
            curr_cislo = curr_cislo + 2
        session.commit()